### ISSUE TITLE
Wallet "passphrase" info gets lost after updating cardano-wallet

### ISSUE THREAD

**Issue by nikolaglumac** [cardano-foundation/cardano-wallet#1701]
# Context
 
We are currently working on a next Daedalus ITN release ([2.4.0-ITN1](https://buildkite.com/input-output-hk/daedalus/builds/12987)) which uses cardano-wallet `031835950a38384b289f3adc43c671a00ef9000b` revision.
We've found an issue that is currently blocking us from proceeding with our release.
Given that you had a wallet created in the current production Daedalus ITN version ([2.3.1-ITN1](https://buildkite.com/input-output-hk/daedalus/builds/11329)) which uses cardano-wallet `8316bffdd05596e8830da9129f3a3907c6fba684` revision and then you update Daedalus to this next release, the wallet's passphrase info is lost - which makes Daedalus think this wallet has no password set.
**There is no option to have a passwordless wallet in any of the Daedalus ITN builds**

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 031835950a38384b289f3adc43c671a00ef9000b |
| Platform     | All         |
| Installation | [Daedalus 2.4.0-ITN1](https://buildkite.com/input-output-hk/daedalus/builds/12987)           |

# Steps to Reproduce

1. Install production Daedalus ITN version: [2.3.1-ITN1](https://buildkite.com/input-output-hk/daedalus/builds/11329)
2. Create/restore a wallet (doesn't matter if it is a Byron/Shelley wallet)
3. Update Daedalus to the pre-production version: [2.4.0-ITN1](https://buildkite.com/input-output-hk/daedalus/builds/12987)
4. Daedalus will ask you to set a password for your existing wallet which will fail as the wallet already has a password set but the Api doesn't return this info correctly.
5. If you then proceed and create a new wallet in this version of Daedalus it will correctly display passphrase info.

### Postman GET wallets response
![screenshot](https://user-images.githubusercontent.com/376611/83407475-11e76c80-a411-11ea-8650-b71e6604e4a2.png)

☝️ as can be seen from this screenshot, the 1st wallet has no "passphrase" attribute, while the 2nd one (created after the update) has.

## Expected behavior

Wallet passphrase info should be preserved after the update.

## Actual behavior
 
Wallet passphrase info is lost after the update.

---

# Resolution 

---

# QA

**Comment by piotr-iohk** [comment]
If I'm not mistaken this is the manifestation of the issue -> https://github.com/input-output-hk/cardano-wallet/issues/1552 (Migration issue on Jormungandr (v2020-03-16 => v2020-04-01 | 07)).

Daedalus ITN version: **2.3.1-ITN1** actually uses cardano-wallet _v2020-03-16._

**Comment by piotr-iohk** [comment]
I see that there is a problem when doing migration v2020-03-16 -> current master (2020.6.2 (git revision: b3cfd5fd523a332bfcb1ac9e63a97bb25bc41dad)):

1. Start v2020-03-16 on Jormungandr.
```
cd cardano-wallet/lib/jormungandr/test/data/jormungandr/test_scripts
cardano-wallet-jormungandr-v2020-03-16 launch --genesis-block ../block0.bin --port 8090 --node-port 8080 --state-dir ./data_launch -- --secret ../secret.yaml --config ../config.yaml
```
2. Create a wallet.
3. Start current version.
On starting we have:
```
[cardano-wallet.wallet-db:Notice:21] [2020-06-03 06:57:18.14 UTC] wallet table does not contain required field 'passphrase_scheme'. Adding this field with a default value of "EncryptWithPBKDF2".
[cardano-wallet.wallet-engine:Error:21] [2020-06-03 06:57:18.14 UTC] Worker has exited unexpectedly: SQLite3 returned ErrorError while attempting to perform prepare "UPDATE wallet SET passphrase_scheme = \"EncryptWithPBKDF2\" WHERE passphrase_scheme IS NULL AND passphrase_last_updated_at IS NOT NULL ;": no such column: passphrase_scheme
```

And trying to list wallet give 500:
```
[cardano-wallet.wallet-db:Info:211] [2020-06-03 06:58:47.85 UTC] Found existing wallet: f425f750be117385fb7c4280dee5cf9be2f0e71c
[cardano-wallet.wallet-db:Info:211] [2020-06-03 06:58:47.85 UTC] Found existing wallet: f425f750be117385fb7c4280dee5cf9be2f0e71c
[cardano-wallet.wallet-db:Notice:211] [2020-06-03 06:58:47.85 UTC] wallet table does not contain required field 'passphrase_scheme'. Adding this field with a default value of "EncryptWithPBKDF2".
SQLite3 returned ErrorError while attempting to perform prepare "UPDATE wallet SET passphrase_scheme = \"EncryptWithPBKDF2\" WHERE passphrase_scheme IS NULL AND passphrase_last_updated_at IS NOT NULL ;": no such column: passphrase_scheme
```

**Comment by piotr-iohk** [comment]
I didn't see a problem when doing this migration path:

v2020-03-16 -> (master before the fix https://github.com/input-output-hk/cardano-wallet/pull/1704) -> (master after the fix https://github.com/input-output-hk/cardano-wallet/pull/1704)

but

v2020-03-16 -> (master after the fix https://github.com/input-output-hk/cardano-wallet/pull/1704)

is problematic... (as described above)

cc: @KtorZ.

**Comment by piotr-iohk** [comment]
fixed with #1717.

**Comment by nathannoble** [comment]
Looks like the issue is back. I restored two wallets into Daedalus and the last one had this error. 

wallet table does not contain required field 'passphrase_scheme'. Adding this field with a default value of "EncryptWithPBKDF2".  

Is there something that can be done to fix this?

**Comment by KtorZ** [comment]
@nathannoble that message in itself isn't an issue. It's part of the normal migration process actually; the server will announce what migrations are being done upon start. When you say, "the last one had this error.", could you give slightly more details?

**Comment by nathannoble** [comment]
@KtorZ It is all good. IOHK support helped me get over it. Apparently I had to delete the State directory. Something I had done before in older version of Daedalus. I understand these issues are growing pains. So if this happens to anyone else. 1. Delete the State Directory then re import your wallets.
