### ISSUE TITLE
Cardano wallet's threads are dying while syncing

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#2730]
# Context
There is a cardano wallet instance with few hundreds wallets connected to.
But you can't syncronize it, because threads are unstable.

## Essential Information

 - **Version**:      v2021-06-11 (git revision: 1532352c75cfe02015873c4c82b0d76eb798dfd8)
 - **Platform**:      LInux
 - **Installation**:  Binaries from release
 - **Network**:      mainnet 

logs piece with an error:

```
[cardano-wallet.wallet-db:Info:1282] [2021-06-21 18:44:56.56 UTC] Starting connection pool for ../../mainnet-wallets/ica.###somewalletid#####.sqlite
[cardano-wallet.wallet-engine:Info:1285] [2021-06-21 18:44:56.57 UTC] 1436aa99: Chain following starting. Requesting intersection using 12 checkpoints, the latest being 6c3f040d<-[bd1b1e9c-32734691#5881200]
[cardano-wallet.wallet-db:Info:1282] [2021-06-21 18:44:56.61 UTC] Closing single database connection (../../mainnet-wallets/ica.###somewalletid#####.sqlite)

[cardano-wallet.wallet-engine:Error:1282] [2021-06-21 18:44:56.61 UTC] Worker has exited: Unhandled exception: user error (Pattern match failure in do expression at src/Cardano/Wallet/DB/Sqlite.hs:596:17-26)

[cardano-wallet.wallet-db:Info:1282] [2021-06-21 18:44:56.61 UTC] Stopping database connection pool ../../mainnet-wallets/ica.###somewalletid#####.sqlite
[cardano-wallet.wallet-db:Info:1298] [2021-06-21 18:44:56.61 UTC] Starting connection pool for ../../mainnet-wallets/ica.###somewalletid#####.sqlite

```

# Steps to Reproduce

1. launch cardano wallet over the node with required version (1.27 for this case)
2. It has to have many wallets attached to. About 400 is enough.

Start command: 
```
cardano-wallet serve --listen-address 127.0.0.1 --port 8100 --node-socket ../../cardano.socket --database ../../mainnet-wallets/ --sync-tolerance 300s --pool-metadata-fetching https://smash.cardano-mainnet.iohk.io --mainnet 

```

## Expected behavior

Wallets are syncing.

## Actual behavior

Wallets are going to bloody pit wit message:
```
That's embarrassing. My associated worker for %somewalletid% is no longer responding. This is not something that is supposed to happen. The worker must have left a trace in the logs of severity 'Error' when it died which might explain the cause. Said differently, this wallet won't be accessible until the server is restarted but there are good chances it'll recover itself upon restart.
```

For the first minute or two the count of connected wallets increases and equals to the real value, but then goes lower and lower. Sometimes it stopes at 20+, but mostly often reaches 0.

---

# Resolution

---

# QA

**Comment by Fell-x27** [comment]
Also log is full of messages like this:
```
[cardano-wallet.pools-engine:Warning:5470] [2021-06-21 19:08:07.99 UTC] Syncing (99.86% percent) Applied 0 blocks, 0 rollbacks in the last 32.135040914s. Currently at slot 32573243. (progress decreased)
```

But the node is online and perfectly synced.

**Comment by Fell-x27** [comment]
Also when you do 
```
cardano-wallet wallet list 
```
You see hundreds of  "[cardano-wallet.wallet-db:Info:6721] [2021-06-21 19:12:04.74 UTC] Found existing wallet: etc" messages, 
but
```
Ok.
[]

```
in the console

and 

```
[cardano-wallet.api-server:Error:7007] [2021-06-21 19:16:25.71 UTC] [RequestId 2] GET /v2/wallets 200 OK in 11.663779015s

```

in the log

**Comment by rvl** [comment]
Thanks for the report and logs @Fell-x27.
It seems to be a problem with error handling.
We are going to investigate this further.

**Comment by piotr-iohk** [comment]
I have reproduced this on testnet and filed Jira ticket: ADP-1013.
It is somewhat similar in observed behavior to ADP-798 (Intermittent 500 Internal Server Error on GET or DELETE Wallet)

**Comment by piotr-iohk** [comment]
This should be fixed in v2021-11-11.

**Comment by danbigthink** [comment]
> This should be fixed in v2021-11-11.

I'm still seeing this in version 2021-11-11, node version 1.30.1

logs:
[cardano-wallet.wallet-db:Info:11817] [2021-12-13 21:18:21.07 UTC] Found existing wallet: xyz
[cardano-wallet.wallet-db:Info:11817] [2021-12-13 21:18:21.07 UTC] Stopping database connection pool /wallet-db/she.abc.sqlite
[cardano-wallet.wallet-db:Info:11817] [2021-12-13 21:18:21.07 UTC] Closing single database connection (/wallet-db/she.abc.sqlite)
[cardano-wallet.api-server:Error:11817] [2021-12-13 21:18:21.08 UTC] [RequestId 12] GET /v2/wallets/abc123 500 Internal Server Error in 0.107682362s
 
checking on my relay node:
cardano-cli query tip --mainnet
"syncProgress": "100.00"

I don't see any sync'ing logs on the wallet server
and clients to the wallet server get this error:
error: That's embarrassing. My associated worker for worker123 is no longer responding. This is not something that is supposed to happen. The worker must have left a trace in the logs of severity 'Error' when it died which might explain the cause. Said differently, this wallet won't be accessible until the server is restarted but there are good chances it'll recover itself upon restart.

This is so frustrating, I've restarted my node, it's at tip, and restarted the wallet server using the command:
serve --mainnet --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0 +RTS -N4 -RTS

which is how I've been running it for a while now.

Any idea what's happening? All of this happened cause I had to restart my node.
